// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sptc.Web.Context;

namespace Sptc.Web.Migrations
{
    [DbContext(typeof(SptcDbContext))]
    [Migration("20200531071830_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sptc.Web.Entity.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<DateTime>("DOB");

                    b.Property<int>("EnrollmentStatus");

                    b.Property<string>("FatherAddress");

                    b.Property<string>("FatherName");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<string>("GuardianAddress");

                    b.Property<string>("GuardianName");

                    b.Property<float>("Height");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("MobileNo");

                    b.Property<string>("MotherAddress");

                    b.Property<string>("MotherMaidenName");

                    b.Property<string>("RelationshipToGuardian");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Registration");
                });
#pragma warning restore 612, 618
        }
    }
}
